apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /Users/syednadeem/Documents/workspace_dockerK8s_traning/dockerK8s_traning/week2/k8s_storage_volume/mounted_folder/
