apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: main-app
          image: nginx:latest
          env:
            - name: CONTAINER_TYPE
              value: main-container
          ports:
            - containerPort: 80
              name: http

        - name: sidecar
          image: busybox:latest
          env:
            - name: CONTAINER_TYPE
              value: sidecar-container          
          command: ["sleep", "3600"]

