apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      initContainers:
        - name: init-setup
          image: busybox:latest
          command: ["sh", "-c", "echo Initializing and sleeping for 10 sec, then i will stop ; sleep 10"]
      containers:
        - name: main-app
          image: nginx:latest

          # Main application container configuration goes here

